#!/bin/bash
# This example tells the server to listen on 30001
podman run -d \
  --name=mineclone2 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 30001:30000/udp \
  -v ${PWD}/worlds:/config/.minetest/worlds \
  --restart unless-stopped \
  ghcr.io/ppreeper/minetest:main

