#!/bin/bash
podman run -d \
  --name=mineclone2 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e CLI_ARGS="--gameid mineclone2 --port 30001" \
  -p 30001:30001/udp \
  -v ${PWD}/worlds:/config/.minetest/worlds \
  --restart unless-stopped \
  localhost/mineclone2:latest